#!/bin/bash

# Produktives Albus stoppen
monit stop mediaclue_pharo

echo "Warte auf Mediaclue-Pharo Ende (Kann Minuten dauern) ..."

# Warten bis pharo Prozesse beendet
while pgrep pharo  > /dev/null; do sleep 1; echo -n "."; done
